apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform infrastructure and services
  sourceRepos:
    - 'https://github.com/Saivarnik12/gitops-eks-platform'
    - 'https://prometheus-community.github.io/helm-charts'
    - 'https://charts.bitnami.com/bitnami'
    - 'https://strimzi.io/charts/'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: read-only
      description: Read-only access
      policies:
        - p, proj:platform:read-only, applications, get, platform/*, allow
